### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.randint(1,51, size=10)

media = np.mean(arr)

desvio_padrao = np.std(arr)

print(arr)
print(media)
print(desvio_padrao)

[12  5 38  1  7 20 34 23 24 28]
19.2
11.923086848631105


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.3253714  0.68984882 0.600764   0.33406124 0.61754738 0.08160105
 0.64537078 0.69644627 0.80439697 0.89790923]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

valor_maximo = np.amax(matriz, axis=1)

print("Matriz 3d:\n", matriz)
print("Valores máximos de cada linha de cada matriz 2d:\n", valor_maximo)

Matriz 3d:
 [[[0.72061353 0.26034766 0.87432806]
  [0.12407222 0.28190151 0.68651002]
  [0.29949807 0.26603203 0.00341457]]

 [[0.16520829 0.00978368 0.49069449]
  [0.97464042 0.84512882 0.26950913]
  [0.00178004 0.53021821 0.98568254]]

 [[0.86555415 0.89791458 0.32113866]
  [0.20441371 0.97766826 0.00656859]
  [0.26661646 0.57883045 0.0367585 ]]]
Valores máximos de cada linha de cada matriz 2d:
 [[0.72061353 0.28190151 0.87432806]
 [0.97464042 0.84512882 0.98568254]
 [0.86555415 0.97766826 0.32113866]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)

print(matriz)

for i in range(5):
  media = np.mean(matriz[i])
  matriz[i] -= media
  
print(matriz)

[[0.0285429  0.63044475 0.87356962 0.25900206 0.04849202]
 [0.25500147 0.83588486 0.83542814 0.08351307 0.30215509]
 [0.45293561 0.37128007 0.12189397 0.32934546 0.1904218 ]
 [0.55105075 0.84544181 0.46557561 0.93789265 0.94704206]
 [0.76267453 0.97626298 0.87694588 0.89257738 0.90263764]]
[[-0.33946737  0.26243448  0.50555935 -0.10900821 -0.31951825]
 [-0.20739505  0.37348833  0.37303161 -0.37888346 -0.16024144]
 [ 0.15976023  0.07810469 -0.17128142  0.03617008 -0.10275358]
 [-0.19834983  0.09604124 -0.28382497  0.18849208  0.19764148]
 [-0.11954515  0.0940433  -0.0052738   0.0103577   0.02041796]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)

print(matriz)
#calculo da media e desvio padrao das diagonais da matriz

diagonalPrincipal = np.diag(matriz) #pega a diagonal da matriz
diagonalSecundaria = np.diag(np.fliplr(matriz))#o fliplr inverte a matriz e assim conseguimnos pegar a diagonal secundaria da matriz principal uma vez que ela foi invertida
mediaDiagonal = np.mean([diagonalPrincipal, diagonalSecundaria]) #faz a média das diagonais que foram extraídas da matriz principal
desvioPadrao = np.std([diagonalPrincipal, diagonalSecundaria]) #calcula o desvio padrao das duas diagonais

print(f'Diagonal Principal: {diagonalPrincipal}')
print(f'Diagonal Secundaria: {diagonalSecundaria}')
print(f'Media diagonais: {mediaDiagonal}')
print(f'Desvio Padrão: {desvioPadrao}')

[[0.82341701 0.22583863 0.36141719 0.18304032]
 [0.01856574 0.135481   0.70518148 0.08718354]
 [0.26745111 0.53002326 0.67627728 0.21478417]
 [0.60244133 0.97897396 0.70839698 0.15695465]]
Diagonal Principal: [0.82341701 0.135481   0.67627728 0.15695465]
Diagonal Secundaria: [0.18304032 0.70518148 0.53002326 0.60244133]
Media diagonais: 0.4766020400350724
Desvio Padrão: 0.25879655085288467
